USE [master]
GO

/****** Object:  Database [Portafolio]    Script Date: 19/11/2018 01:30:55 p. m. ******/
CREATE DATABASE [Portafolio]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Portafolio', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Portafolio.mdf' , SIZE = 12352KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Portafolio_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\Portafolio_log.ldf' , SIZE = 104000KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Portafolio] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Portafolio].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Portafolio] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Portafolio] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Portafolio] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Portafolio] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Portafolio] SET ARITHABORT OFF 
GO

ALTER DATABASE [Portafolio] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [Portafolio] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Portafolio] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Portafolio] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Portafolio] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Portafolio] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Portafolio] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Portafolio] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Portafolio] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Portafolio] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Portafolio] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Portafolio] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Portafolio] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Portafolio] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Portafolio] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Portafolio] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Portafolio] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Portafolio] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Portafolio] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Portafolio] SET  MULTI_USER 
GO

ALTER DATABASE [Portafolio] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Portafolio] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Portafolio] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Portafolio] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Portafolio] SET  READ_WRITE 
GO